from flasker import app, db
from flasker import app, db


class Applicant(db.Model):
	firstname = db.Column(db.String(30),nullable=False)
	lastname = db.Column(db.String(30),nullable=False)
	studusername = db.Column(db.String(30),primary_key=True)
	gender = db.Column(db.String(10),nullable=False)
	dob = db.Column(db.String(30),nullable=False)
	age = db.Column(db.Integer,nullable=False)
	emailaddress = db.Column(db.String(30),nullable=False)
	parentmobno = db.Column(db.String(12),nullable=False)
	personalno = db.Column(db.String(12),nullable=False)
	alternateno = db.Column(db.String(12),nullable=False)
	nationality = db.Column(db.String(20),nullable= False)
	city = db.Column(db.String(30),nullable=False)
	state = db.Column(db.String(30),nullable=False)
	address_line1 = db.Column(db.String(100),nullable=False)
	address_line2 = db.Column(db.String(100),nullable=False)
	familyincome = db.Column(db.String(20),nullable=False)

class Student(db.Model):
	studusername = db.Column(db.String(50),(db.ForeignKey("Applicant.studusername")), nullable = False, primary_key = True)
	photo = db.Column(db.String(78),nullable= False)
	emailaddress = db.Column(db.String(30),nullable=False)
	currentaddress = db.Column(db.String(100),nullable=False)
	fathername = db.Column(db.String(100),nullable=False)
	fatherage = db.Column(db.Integer,nullable=False)
	fatherincome = db.Column(db.Integer,nullable=False)
	fatheroccupationdetails =  db.Column(db.String(100),nullable=False)
	fatheroccupationaddress =  db.Column(db.String(100),nullable=False)
	motherrname =  db.Column(db.String(50),nullable=False)
	motherage = db.Column(db.Integer,nullable=False)
	motheroccupationdetails =  db.Column(db.String(100),nullable=False)
	motherincome = db.Column(db.Integer,nullable=False)
	motheroccupationdetails =  db.Column(db.String(100),nullable=False)
	motheroccupationaddress =  db.Column(db.String(100),nullable=False)
	totalfamilymembers =  db.Column(db.Integer,nullable=False)
	educationcourse =  db.Column(db.String(100),nullable=False)
	yearorstd =  db.Column(db.String(30),nullable=False)
	institutename =  db.Column(db.String(100),nullable=False)
	collegeorschoolfees =  db.Column(db.Integer,nullable=False)
	coachingclassfees =  db.Column(db.Integer,nullable=False)
	examfees =  db.Column(db.Integer,nullable=False)
	otherfees =  db.Column(db.Integer,nullable=False)
	totalfees =  db.Column(db.Integer,nullable=False)
	helpfromgoverment = db.Column(db.String(10),nullable=False)
	owncontribution = db.Column(db.String(10),nullable=False)
	netamountrequired = db.Column(db.Integer,nullable=False)
	extracurricular = db.Column(db.String(100),nullable=False)
	reference1name = db.Column(db.String(50),nullable=False)
	reference1phoneno = db.Column(db.String(10),nullable=False)
	reference1address = db.Column(db.String(100),nullable=False)
	reference2name = db.Column(db.String(50),nullable=False)
	reference2phoneno = db.Column(db.String(10),nullable=False)
	reference2address = db.Column(db.String(100),nullable=False)
	incomecertificate = db.Column(db.String(78),nullable=False)
	uploadadharcard = db.Column(db.String(78),nullable=False)
	uploadrationcard = db.Column(db.String(78),nullable=False)
	uploadelectricitybill = db.Column(db.String(78),nullable=False)
	uploadbirthcertificate = db.Column(db.String(78),nullable=False)

class Donor(db.Model):
	fname = db.Column(db.String(30),nullable = False)
	lname = db.Column(db.String(30),nullable = False)
	donorusername = db.Column(db.String(30),primary_key=True)
	password = db.Column(db.String(20),nullable = False)
	occupation = db.Column(db.String(30),nullable = False)
	donatedamount = db.Column(db.String(20), nullable = False)
	mobileno = db.Column(db.String(12),nullable=False)

class Committeemembers(db.Model):
	fname = db.Column(db.String(30),nullable = False)
	lname = db.Column(db.String(30),nullable = False)
	role =  db.Column(db.String(30),nullable = False)
	cusername = db.Column(db.String(30),primary_key=True)
	password = db.Column(db.String(20),nullable= False)
	emailaddress = db.Column(db.String(40),nullable= False)
	mobileno = db.Column(db.String(12),nullable=False)

class Donates(db.Model):
	studusername = db.Column(db.String(30), primary_key = True)
	donorusername = db.Column(db.String(30), (db.ForeignKey("Donor.donorusername")))
	amount = db.Column(db.Integer,nullable=False)

class Volunteer(db.Model):
	fname = db.Column(db.String(30),nullable=False)
	lname = db.Column(db.String(30),nullable=False)
	vusername = db.Column(db.String(30),primary_key=True)
	password = db.Column(db.String(20),nullable=False)
	emailaddress = db.Column(db.String(40),nullable=False)
	mobileno = db.Column(db.String(12),nullable=False)

