"""User tables

Revision ID: 941a95528913
Revises: 
Create Date: 2018-07-22 03:46:16.487735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941a95528913'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applicant_password'), 'applicant', ['password'], unique=True)
    op.create_index(op.f('ix_applicant_username'), 'applicant', ['username'], unique=True)
    op.create_table('committee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_committee_password'), 'committee', ['password'], unique=True)
    op.create_index(op.f('ix_committee_username'), 'committee', ['username'], unique=True)
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donor_password'), 'donor', ['password'], unique=True)
    op.create_index(op.f('ix_donor_username'), 'donor', ['username'], unique=True)
    op.create_table('educon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_educon_password'), 'educon', ['password'], unique=True)
    op.create_index(op.f('ix_educon_username'), 'educon', ['username'], unique=True)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_password'), 'student', ['password'], unique=True)
    op.create_index(op.f('ix_student_username'), 'student', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_username'), table_name='student')
    op.drop_index(op.f('ix_student_password'), table_name='student')
    op.drop_table('student')
    op.drop_index(op.f('ix_educon_username'), table_name='educon')
    op.drop_index(op.f('ix_educon_password'), table_name='educon')
    op.drop_table('educon')
    op.drop_index(op.f('ix_donor_username'), table_name='donor')
    op.drop_index(op.f('ix_donor_password'), table_name='donor')
    op.drop_table('donor')
    op.drop_index(op.f('ix_committee_username'), table_name='committee')
    op.drop_index(op.f('ix_committee_password'), table_name='committee')
    op.drop_table('committee')
    op.drop_index(op.f('ix_applicant_username'), table_name='applicant')
    op.drop_index(op.f('ix_applicant_password'), table_name='applicant')
    op.drop_table('applicant')
    # ### end Alembic commands ###
